<?php
/**
 * 模组管理页面（内容模板）
 *
 * @var \Weline\Framework\View\Template $this
 */
?>

<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'><?= __('模组管理') ?></h4>
            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><span><?= __('系统') ?></span></li>
                    <li class='breadcrumb-item active'><?= __('模组管理') ?></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div>

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'><?= __('模组管理') ?></h4>
                <p class='card-title-desc'><?= __('系统中安装的模组。') ?></p>
                <?php
                $modules = $this->getData('modules');
                ?>
                <div class='table-rep-plugin'>
                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                            <thead>
                            <tr>
                                <th data-priority='1'><?= __('模组名') ?></th>
                                <th data-priority='3'><?= __('状态') ?></th>
                                <th data-priority='1'><?= __('命名空间') ?></th>
                                <th data-priority='3'><?= __('安装位置') ?></th>
                                <th data-priority='3'><?= __('目录') ?></th>
                                <th data-priority='3'><?= __('路由') ?></th>
                                <th data-priority='3'><?= __('版本') ?></th>
                                <th data-priority='3'><?= __('描述') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($modules as $name => $info) :
                                ?>
                                <tr>
                                    <td></td>
                                    <th colspan="4" class='co-name'><?= $name ?></th>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><?= $info['status'] ?></td>
                                    <td><?= $info['namespace_path'] ?></td>
                                    <td><?= $info['base_path'] ?></td>
                                    <td><?= $info['path'] ?></td>
                                    <td><?= $info['router'] ?></td>
                                    <td><?= $info['version'] ?></td>
                                    <td><?= $info['description'] ?></td>
                                </tr>
                            <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
