<?php
/**
 * CMS内容管理页面（内容模板）
 *
 * @var \Weline\Framework\View\Template $this
 */
?>

<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'><?= __('Cms内容管理') ?></h4>
            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><span><?= __('系统') ?></span></li>
                    <li class='breadcrumb-item active'><?= __('内容管理') ?></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div>

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'><?= __('Cms内容管理') ?></h4>
                <p class='card-title-desc'><?= __('后台可视化建设页面等的内容管理。') ?></p>
                <div class='col-lg-12'>
                    <div class='card alert border p-0 mb-0'>
                        <div class='card-header bg-soft-success'>
                            <div class='d-flex'>
                                <div class='flex-grow-1'>
                                    <h5 class='font-size-16 text-success my-1'>等待开发中...</h5>
                                </div>
                                <div class='flex-shrink-0'>
                                    <button type='button' class='btn-close' data-bs-dismiss='alert'
                                            aria-label='Close'></button>
                                </div>
                            </div>
                        </div>

                        <div class='card-body'>
                            <div class='text-center'>
                                <div class='mb-4'>
                                    <i class='mdi mdi-checkbox-marked-circle-outline display-4 text-success'></i>
                                </div>
                                <h4 class='alert-heading font-18'>马上就好！</h4>
                                <p class='mb-0'>有兴趣可以一起参与！</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
