<!doctype html>
<html lang='en'>

<head>

    <meta charset='utf-8'/>
    <title>@lang(网站维护中...)</title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta content='Premium Multipurpose Admin & WelineFramework' name='description'/>
    <meta content='秋枫雁飞(aiweline)' name='author'/>
    <!-- App favicon -->
    <link rel='shortcut icon' href='@static(assets/images/favicon.ico)'>

    <!-- Bootstrap Css -->
    <link href='@static(assets/css/bootstrap.min.css)' id='bootstrap-style' rel='stylesheet' type='text/css'/>
    <!-- Icons Css -->
    <link href='@static(assets/css/icons.min.css)' rel='stylesheet' type='text/css'/>
    <!-- App Css-->
    <link href='@static(assets/css/app.min.css)' id='app-style' rel='stylesheet' type='text/css'/>

</head>

<body>

<div class='py-5'>

    <div class='container'>
        <div class='row justify-content-center'>
            <div class='col-md-8 col-lg-6 col-xl-5'>
                <div class='text-center mt-sm-5 mb-4'>
                    <a href="@admin-url('admin/template/upzet/index.html')" class=''>
                        <img src='@static(assets/images/logo-dark.png)' alt=''
                             class='auth-logo logo-dark mx-auto'>
                        <img src='@static(assets/images/logo-light.png)' alt=''
                             class='auth-logo logo-light mx-auto'>
                    </a>
                    <p class='mt-3'>
                        <lang>响应式 Bootstrap 5 管理后台</lang>
                    </p>

                    <div class='mt-5'>
                        <div class='mb-4'>
                            <i class='ri-tools-fill display-3'></i>
                        </div>
                        <h4>
                            <lang>网站正在维护中...</lang>
                        </h4>
                        <p>
                            <lang>请稍等片刻</lang>
                        </p>

                        <div class='mt-4 pt-2'>
                            <a href="@admin-url('admin/template/upzet/index.html')" class='btn btn-primary'>
                                <lang>返回首页</lang>
                            </a>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <!-- end row -->

        <div class='row mt-4'>
            <div class='col-md-4'>
                <div class='text-center'>
                    <div class='card-body'>
                        <div class='avatar-sm mx-auto mb-4'>
                            <div class='avatar-title rounded-circle'>
                                <i class='ri-broadcast-line font-size-24'></i>
                            </div>
                        </div>
                        <h5 class='font-size-15 text-uppercase'>
                            <lang>为什么网站会处于维护模式？</lang>
                        </h5>
                        <p class='mb-0'>
                            <lang>网站可能发生系统升级事件，或者大多数的内容发生变化，程序员们正在维护或者升级数据以提供更加优质的服务。</lang>
                        </p>
                    </div>
                </div>
            </div>
            <div class='col-md-4'>
                <div class='text-center'>
                    <div class='card-body'>
                        <div class='avatar-sm mx-auto mb-4'>
                            <div class='avatar-title rounded-circle'>
                                <i class='ri-time-line font-size-24'></i>
                            </div>
                        </div>
                        <h5 class='font-size-15 text-uppercase'>
                            <lang>多久能够恢复？</lang>
                        </h5>
                        <p class='mb-0'>
                            <lang>大部分的网站升级活动都只有几分钟甚至几秒钟的时间。</lang>
                        </p>
                    </div>
                </div>
            </div>
            <div class='col-md-4'>
                <div class='text-center'>
                    <div class='card-body'>
                        <div class='avatar-sm mx-auto mb-4'>
                            <div class='avatar-title rounded-circle'>
                                <i class='ri-mail-line font-size-24'></i>
                            </div>
                        </div>
                        <h5 class='font-size-15 text-uppercase'>
                            <lang>需要帮助吗？</lang>
                        </h5>
                        <p class='mb-0'>
                            <lang>如果你长期看到这个页面，对网站存在疑惑，请联系：</lang>
                            <a
                                    href="mailto:aiweline@qq.com"
                                    class="text-decoration-underline">aiweline@qq.com</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->

    </div>
    <!-- end container -->

</div>
<!-- end auth-page -->

<!-- JAVASCRIPT -->
<script src="@static(assets/libs/jquery/jquery.min.js)"></script>
<script src="@static(assets/libs/bootstrap/js/bootstrap.bundle.min.js)"></script>
<script src="@static(assets/libs/metismenu/metisMenu.min.js)"></script>
<script src="@static(assets/libs/simplebar/simplebar.min.js)"></script>
<script src="@static(assets/libs/node-waves/waves.min.js)"></script>

</body>
</html>
