        </div>
        <!-- end page content-->
    </div>
    <!-- end main content-->
</div>
<!-- END layout-wrapper -->

<!--右边栏-->
<w:template>Weline_Admin::common/right-sidebar.phtml</w:template>

<!-- jquery.vectormap map -->
<w:js>Weline_Admin::assets/libs/jqvmap/jquery.vmap.min.js</w:js>
<w:js>Weline_Admin::assets/libs/jqvmap/maps/jquery.vmap.usa.js</w:js>
<w:js>Weline_Admin::assets/libs/jqvmap/maps/jquery.vmap.usa.js</w:js>
<!--页脚-->
<w:template>Weline_Admin::common/footer.phtml</w:template>
</body>
</html>


